unit dmPubl;

interface

uses
  SysUtils, Classes, DB, IBEvents, FMTBcd, Provider, SqlExpr,
  DBClient, SimpleDS, HttpXmlDataSet;

type
  TpublData = class(TDataModule)
    qryObjavVerstkaDifference: TSQLQuery;
    dsObjavVerstkaDifference: TDataSource;
    cdsObjavSverstano: TClientDataSet;
    dsObjavSverstano: TDataSource;
    qry: TSQLQuery;
    cdsChangeCount: TClientDataSet;
    cdsChangeCountCHANGE_COUNT: TIntegerField;
    cdsChangeCountRB_ID: TIntegerField;
    cdsChangeCountRB_NAME: TStringField;
    dsChangeCount: TDataSource;
    tblGazetaCurrent: TSimpleDataSet;
    tblGazetaCurrentGZ_ID: TSmallintField;
    tblGazetaCurrentGZ_NAME: TStringField;
    tblGazetaCurrentGZ_NAME_SHORT: TStringField;
    dsGazetaCurrent: TDataSource;
    spObjavSverstana: TSQLStoredProc;
    spNextExportID: TSQLStoredProc;
    cdsObjavOrder: TClientDataSet;
    dsObjavOrder: TDataSource;
    tblAgent: TSimpleDataSet;
    dsAgent: TDataSource;
    tblAgentAG_ID: TIntegerField;
    tblAgentAG_NAME: TStringField;
    tblAgentAG_IS_REMOTE: TSmallintField;
    qryObjavSverstano: TSQLQuery;
    qryObjavSverstanoAG_ID: TIntegerField;
    qryObjavSverstanoSD_ID: TIntegerField;
    qryObjavSverstanoOB_ID: TIntegerField;
    qryObjavSverstanoRB_ID: TIntegerField;
    qryObjavSverstanoSD_ID_COMPOUND: TStringField;
    qryObjavSverstanoOB_COMMENT: TStringField;
    qryObjavSverstanoOBJAV_TEXT: TStringField;
    qryObjavSverstanoPD_ID: TIntegerField;
    prvObjavSverstano: TDataSetProvider;
    cdsObjavSverstanoAG_ID: TIntegerField;
    cdsObjavSverstanoSD_ID: TIntegerField;
    cdsObjavSverstanoOB_ID: TIntegerField;
    cdsObjavSverstanoPD_ID: TIntegerField;
    cdsObjavSverstanoRB_ID: TIntegerField;
    cdsObjavSverstanoSD_ID_COMPOUND: TStringField;
    cdsObjavSverstanoOB_COMMENT: TStringField;
    cdsObjavSverstanoOBJAV_TEXT: TStringField;
    prvObjavVerstkaDifference: TDataSetProvider;
    cdsObjavVerstkaDifference: TClientDataSet;
    qryObjavVerstkaDifferenceAG_ID: TIntegerField;
    qryObjavVerstkaDifferenceSD_ID: TIntegerField;
    qryObjavVerstkaDifferenceOB_ID: TIntegerField;
    qryObjavVerstkaDifferencePD_ID: TIntegerField;
    qryObjavVerstkaDifferenceRB_ID: TIntegerField;
    qryObjavVerstkaDifferenceSD_ID_COMPOUND: TStringField;
    qryObjavVerstkaDifferenceDIAGNOZ: TSmallintField;
    qryObjavVerstkaDifferenceOB_COMMENT: TStringField;
    qryObjavVerstkaDifferenceRB_NAME_SHORT: TStringField;
    qryObjavVerstkaDifferenceOBJAV_TEXT: TStringField;
    cdsObjavVerstkaDifferenceAG_ID: TIntegerField;
    cdsObjavVerstkaDifferenceSD_ID: TIntegerField;
    cdsObjavVerstkaDifferenceOB_ID: TIntegerField;
    cdsObjavVerstkaDifferencePD_ID: TIntegerField;
    cdsObjavVerstkaDifferenceRB_ID: TIntegerField;
    cdsObjavVerstkaDifferenceSD_ID_COMPOUND: TStringField;
    cdsObjavVerstkaDifferenceDIAGNOZ: TSmallintField;
    cdsObjavVerstkaDifferenceOB_COMMENT: TStringField;
    cdsObjavVerstkaDifferenceRB_NAME_SHORT: TStringField;
    cdsObjavVerstkaDifferenceOBJAV_TEXT: TStringField;
    qryObjavVerstkaDifferenceDIAGNOZ_NAME: TStringField;
    cdsObjavVerstkaDifferenceDIAGNOZ_NAME: TStringField;
    qryChangeCount: TSQLQuery;
    prvChangeCount: TDataSetProvider;
    qryChangeCountCHANGE_COUNT: TIntegerField;
    qryChangeCountRB_ID: TIntegerField;
    qryChangeCountRB_NAME: TStringField;
    qryObjavOrder: TSQLQuery;
    prvObjavOrder: TDataSetProvider;
    qryObjavOrderAG_ID: TIntegerField;
    qryObjavOrderSD_ID: TIntegerField;
    qryObjavOrderOB_ID: TIntegerField;
    qryObjavOrderSD_ID_COMPOUND: TStringField;
    qryObjavOrderOS_NAME: TStringField;
    qryObjavOrderOBJAV_TEXT: TStringField;
    cdsObjavOrderAG_ID: TIntegerField;
    cdsObjavOrderSD_ID: TIntegerField;
    cdsObjavOrderOB_ID: TIntegerField;
    cdsObjavOrderSD_ID_COMPOUND: TStringField;
    cdsObjavOrderOS_NAME: TStringField;
    cdsObjavOrderOBJAV_TEXT: TStringField;
    qryObjavOrderOB_ORDER: TFloatField;
    cdsObjavOrderOB_ORDER: TFloatField;
    qryObjavSverstanoSD_SHOW_CUST_ID: TSmallintField;
    qryObjavSverstanoCU_ID_COMPOUND: TStringField;
    qryObjavSverstanoCU_INFO: TStringField;
    cdsObjavSverstanoSD_SHOW_CUST_ID: TSmallintField;
    cdsObjavSverstanoCU_ID_COMPOUND: TStringField;
    cdsObjavSverstanoCU_INFO: TStringField;
    qryCustInfoList: TSimpleDataSet;
    dsCustInfoList: TDataSource;
    qryCustInfoListCU_ID_COMPOUND: TStringField;
    qryCustInfoListCU_INFO: TStringField;
    qryObjavForKA: TSQLQuery;
    qryObjavForKAAG_ID: TIntegerField;
    qryObjavForKASD_ID: TIntegerField;
    qryObjavForKAOB_ID: TIntegerField;
    qryObjavForKARB_ID: TIntegerField;
    qryObjavForKASD_ID_COMPOUND: TStringField;
    qryObjavForKAOB_COMMENT: TStringField;
    qryObjavForKACU_ID_COMPOUND: TStringField;
    qryObjavForKACU_NAME: TStringField;
    qryObjavForKARB_NAME_SHORT: TStringField;
    qryObjavForKAOBJAV_TEXT: TStringField;
    prvObjavForKA: TDataSetProvider;
    cdsObjavForKA: TClientDataSet;
    cdsObjavForKAAG_ID: TIntegerField;
    cdsObjavForKASD_ID: TIntegerField;
    cdsObjavForKAOB_ID: TIntegerField;
    cdsObjavForKARB_ID: TIntegerField;
    cdsObjavForKASD_ID_COMPOUND: TStringField;
    cdsObjavForKAOB_COMMENT: TStringField;
    cdsObjavForKACU_ID_COMPOUND: TStringField;
    cdsObjavForKACU_NAME: TStringField;
    cdsObjavForKARB_NAME_SHORT: TStringField;
    cdsObjavForKAOBJAV_TEXT: TStringField;
    dsObjavForKA: TDataSource;
    qryCustKAInfo: TSimpleDataSet;
    dsCustKAInfo: TDataSource;
    qryCustKAInfoCU_NAME: TStringField;
    qryCustKAInfoCU_KA_INFO_FULL: TStringField;
    qryObjavForKACU_KA_INFO_SHORT: TStringField;
    cdsObjavForKACU_KA_INFO_SHORT: TStringField;
    qryObjavVerstkaDifferenceSD_SHOW_CUST_ID: TSmallintField;
    qryObjavVerstkaDifferenceCU_ID_COMPOUND: TStringField;
    qryObjavVerstkaDifferenceCU_INFO: TStringField;
    cdsObjavVerstkaDifferenceSD_SHOW_CUST_ID: TSmallintField;
    cdsObjavVerstkaDifferenceCU_ID_COMPOUND: TStringField;
    cdsObjavVerstkaDifferenceCU_INFO: TStringField;
    qryModuliVerstka: TSQLQuery;
    prvModuliVerstka: TDataSetProvider;
    cdsModuliVerstka: TClientDataSet;
    dsModuliVerstka: TDataSource;
    qryModuliVerstkaAG_ID: TIntegerField;
    qryModuliVerstkaSD_ID: TIntegerField;
    qryModuliVerstkaOB_ID: TIntegerField;
    qryModuliVerstkaRB_ID: TIntegerField;
    qryModuliVerstkaFM_ID: TIntegerField;
    qryModuliVerstkaCONTENT_ID: TIntegerField;
    qryModuliVerstkaAG_NAME: TStringField;
    qryModuliVerstkaSD_ID_COMPOUND: TStringField;
    qryModuliVerstkaRB_NAME_SHORT: TStringField;
    qryModuliVerstkaFM_NAME: TStringField;
    qryModuliVerstkaPODACHA_NUMS: TStringField;
    cdsModuliVerstkaAG_ID: TIntegerField;
    cdsModuliVerstkaSD_ID: TIntegerField;
    cdsModuliVerstkaOB_ID: TIntegerField;
    cdsModuliVerstkaRB_ID: TIntegerField;
    cdsModuliVerstkaFM_ID: TIntegerField;
    cdsModuliVerstkaCONTENT_ID: TIntegerField;
    cdsModuliVerstkaAG_NAME: TStringField;
    cdsModuliVerstkaSD_ID_COMPOUND: TStringField;
    cdsModuliVerstkaRB_NAME_SHORT: TStringField;
    cdsModuliVerstkaFM_NAME: TStringField;
    cdsModuliVerstkaPODACHA_NUMS: TStringField;
    qryModuliVerstkaCONTENT_PICTURE: TBlobField;
    cdsModuliVerstkaCONTENT_PICTURE: TBlobField;
    qryModuliVerstkaOBJAV_HAS_ATTENTION: TSmallintField;
    cdsModuliVerstkaOBJAV_HAS_ATTENTION: TSmallintField;
    qryObjavVerstkaDifferenceGZ_ID: TSmallintField;
    qryObjavSverstanoGZ_ID: TSmallintField;
    cdsObjavVerstkaDifferenceGZ_ID: TSmallintField;
    cdsObjavSverstanoGZ_ID: TSmallintField;
    qryModuliVerstkaGZ_ID: TSmallintField;
    cdsModuliVerstkaGZ_ID: TSmallintField;
    qryNavchCourse: TSQLQuery;
    dsNavchCourse: TDataSource;
    cdsNavchCourse: TClientDataSet;
    prvNavchCourse: TDataSetProvider;
    qryNavchCourseAG_NAME: TStringField;
    qryNavchCourseRB_NAME: TStringField;
    qryNavchCourseCU_INFO: TStringField;
    qryNavchCourseOB_TEXT: TStringField;
    cdsNavchCourseAG_NAME: TStringField;
    cdsNavchCourseRB_NAME: TStringField;
    cdsNavchCourseCU_INFO: TStringField;
    cdsNavchCourseOB_TEXT: TStringField;
    qryNavchCourseAG_ID: TIntegerField;
    qryNavchCourseSD_ID: TIntegerField;
    qryNavchCourseOB_ID: TIntegerField;
    qryNavchCourseGZ_ID: TSmallintField;
    cdsNavchCourseAG_ID: TIntegerField;
    cdsNavchCourseSD_ID: TIntegerField;
    cdsNavchCourseOB_ID: TIntegerField;
    cdsNavchCourseGZ_ID: TSmallintField;
    qryObjavSverstanoFM_ID: TSmallintField;
    cdsObjavSverstanoFM_ID: TSmallintField;
    qryObjavVerstkaDifferenceFM_ID: TSmallintField;
    cdsObjavVerstkaDifferenceFM_ID: TSmallintField;
    cdsInetImport: THttpXMLDataSet;
    dsRubrikaVerstka: TDataSource;
    tblRubrikaVerstka: TClientDataSet;
    tblRubrikaVerstkaRB_ID: TIntegerField;
    tblRubrikaVerstkaRB_NAME: TStringField;
    tblRubrikaVerstkaRB_NAME_SHORT: TStringField;
    tblRubrikaVerstkaRB_COST_COEFF: TFloatField;
    tblRubrikaVerstkaRB_IS_OBLOGKA: TSmallintField;
    tblRubrikaVerstkaGZ_ID: TIntegerField;
    tblRubrikaVerstkaRB_IS_LOCKABLE: TSmallintField;
    dsRubrikaKorrektura: TDataSource;
    tblRubrikaKorrektura: TClientDataSet;
    IntegerField1: TIntegerField;
    StringField1: TStringField;
    StringField2: TStringField;
    FloatField1: TFloatField;
    SmallintField1: TSmallintField;
    IntegerField2: TIntegerField;
    SmallintField2: TSmallintField;
    dsCustForObjavExport: TDataSource;
    qryCustForObjavExport: TSQLQuery;
    cdsCustForObjavExport: TClientDataSet;
    prvCustForObjavExport: TDataSetProvider;
    qryCustForObjavExportAG_ID: TIntegerField;
    qryCustForObjavExportCU_ID: TIntegerField;
    qryCustForObjavExportAG_NAME: TStringField;
    qryCustForObjavExportCU_NAME: TStringField;
    qryCustForObjavExportCU_ID_CMP: TStringField;
    cdsCustForObjavExportAG_ID: TIntegerField;
    cdsCustForObjavExportCU_ID: TIntegerField;
    cdsCustForObjavExportAG_NAME: TStringField;
    cdsCustForObjavExportCU_NAME: TStringField;
    cdsCustForObjavExportCU_ID_CMP: TStringField;
    cdsObjavExportCust: TClientDataSet;
    dsObjavExportCust: TDataSource;
    qryObjavExportCust: TSQLQuery;
    prvObjavExportCust: TDataSetProvider;
    qryObjavExportCustAG_ID: TIntegerField;
    qryObjavExportCustSD_ID: TIntegerField;
    qryObjavExportCustOB_ID: TIntegerField;
    qryObjavExportCustOB_STATE: TSmallintField;
    qryObjavExportCustOB_COMMENT: TStringField;
    qryObjavExportCustOB_TEXT: TStringField;
    qryObjavExportCustCU_ID: TIntegerField;
    qryObjavExportCustRB_NAME_SHORT: TStringField;
    cdsObjavExportCustAG_ID: TIntegerField;
    cdsObjavExportCustSD_ID: TIntegerField;
    cdsObjavExportCustOB_ID: TIntegerField;
    cdsObjavExportCustOB_STATE: TSmallintField;
    cdsObjavExportCustOB_COMMENT: TStringField;
    cdsObjavExportCustOB_TEXT: TStringField;
    cdsObjavExportCustCU_ID: TIntegerField;
    cdsObjavExportCustRB_NAME_SHORT: TStringField;
    qryModuliExportCust: TSQLQuery;
    prvModuliExportCust: TDataSetProvider;
    cdsModuliExportCust: TClientDataSet;
    dsModuliExportCust: TDataSource;
    qryModuliExportCustAG_ID: TIntegerField;
    qryModuliExportCustSD_ID: TIntegerField;
    qryModuliExportCustOB_ID: TIntegerField;
    qryModuliExportCustRB_ID: TIntegerField;
    qryModuliExportCustFM_ID: TIntegerField;
    qryModuliExportCustCONTENT_ID: TIntegerField;
    qryModuliExportCustRB_NAME_SHORT: TStringField;
    qryModuliExportCustCONTENT_PICTURE: TBlobField;
    cdsModuliExportCustAG_ID: TIntegerField;
    cdsModuliExportCustSD_ID: TIntegerField;
    cdsModuliExportCustOB_ID: TIntegerField;
    cdsModuliExportCustRB_ID: TIntegerField;
    cdsModuliExportCustFM_ID: TIntegerField;
    cdsModuliExportCustCONTENT_ID: TIntegerField;
    cdsModuliExportCustRB_NAME_SHORT: TStringField;
    cdsModuliExportCustCONTENT_PICTURE: TBlobField;
    qryObjavSverstanoFM_NAME: TStringField;
    cdsObjavSverstanoFM_NAME: TStringField;
    qryObjavVerstkaDifferenceFM_NAME: TStringField;
    cdsObjavVerstkaDifferenceFM_NAME: TStringField;
    qryObjavSverstanoRB_NAME_SHORT: TStringField;
    cdsObjavSverstanoRB_NAME_SHORT: TStringField;
    qryObjavForKorrektura: TSQLQuery;
    IntegerField3: TIntegerField;
    IntegerField4: TIntegerField;
    IntegerField5: TIntegerField;
    SmallintField3: TSmallintField;
    StringField3: TStringField;
    StringField4: TStringField;
    SmallintField4: TSmallintField;
    StringField5: TStringField;
    StringField6: TStringField;
    StringField7: TStringField;
    StringField13: TStringField;
    StringField14: TStringField;
    IntegerField6: TIntegerField;
    SmallintField5: TSmallintField;
    SmallintField6: TSmallintField;
    IntegerField7: TIntegerField;
    qryObjavForKorrekturaIS_ID: TIntegerField;
    dsObjavForKorrekturaNew: TDataSource;
    qIssue: TSQLQuery;
    prvObjavForKorrektura: TDataSetProvider;
    cdsObjavForKorrektura: TClientDataSet;
    cdsObjavForKorrekturaAG_ID: TIntegerField;
    cdsObjavForKorrekturaSD_ID: TIntegerField;
    cdsObjavForKorrekturaOB_ID: TIntegerField;
    cdsObjavForKorrekturaOB_STATE: TSmallintField;
    cdsObjavForKorrekturaOB_COMMENT: TStringField;
    cdsObjavForKorrekturaAG_NAME: TStringField;
    cdsObjavForKorrekturaAG_IS_REMOTE: TSmallintField;
    cdsObjavForKorrekturaSD_ID_COMPOUND: TStringField;
    cdsObjavForKorrekturaRB_NAME_SHORT: TStringField;
    cdsObjavForKorrekturaFM_NAME: TStringField;
    cdsObjavForKorrekturaGZ_NAME_SHORT: TStringField;
    cdsObjavForKorrekturaPODACHA_NUMS: TStringField;
    cdsObjavForKorrekturaCU_ID: TIntegerField;
    cdsObjavForKorrekturaGZ_ID: TSmallintField;
    cdsObjavForKorrekturaRB_IS_LOCKABLE: TSmallintField;
    cdsObjavForKorrekturaSR_IS_CURRENT_ISSUE: TIntegerField;
    cdsObjavForKorrekturaIS_ID: TIntegerField;
    qryObjavForKorrekturasd_num: TStringField;
    cdsObjavForKorrekturasd_num: TStringField;
    qryObjavVerstkaDifferenceSD_NUM: TStringField;
    cdsObjavVerstkaDifferenceSD_NUM: TStringField;
    qryObjavSverstanoSD_NUM: TStringField;
    cdsObjavSverstanoSD_NUM: TStringField;
    qryModuliVerstkaSD_NUM: TStringField;
    cdsModuliVerstkaSD_NUM: TStringField;
    qryObjavForKASD_NUM: TStringField;
    cdsObjavForKASD_NUM: TStringField;
    qryNavchCourseSD_NUM: TStringField;
    cdsNavchCourseSD_NUM: TStringField;
    qryModuliExportCustSD_NUM: TStringField;
    qryModuliVerstkaEXTENSION: TStringField;
    cdsModuliVerstkaEXTENSION: TStringField;
    qSTTable: TSQLQuery;
    prvSTTable: TDataSetProvider;
    cdsSTTable: TClientDataSet;
    dsSTTable: TDataSource;
    cdsSTTableSITE_VACANCY_NAME: TStringField;
    cdsSTTableSITE_OBJAV_TEXT: TStringField;
    cdsSTTableSITE_TEL: TStringField;
    cdsSTTableSITE_ZP: TIntegerField;
    cdsSTTableRB_NAME_ENG: TStringField;
    procedure qryObjavForNaborSDS_NAMEGetText(Sender: TField;
      var Text: String; DisplayText: Boolean);
    procedure qrySdelkaForKorrekturaSD_COMMENTGetText(Sender: TField;
      var Text: String; DisplayText: Boolean);
    procedure qryChangeCountLIST_TEXTGetText(Sender: TField;
      var Text: String; DisplayText: Boolean);
    procedure cdsSdelkaSverstanaOBJAV_TEXTGetText(Sender: TField;
      var Text: String; DisplayText: Boolean);
    procedure qryFindOldObjav1OB_TEXTGetText(Sender: TField;
      var Text: String; DisplayText: Boolean);
    procedure prvObjavOrderGetTableName(Sender: TObject; DataSet: TDataSet;
      var TableName: String);
    procedure prvObjavSverstanoGetTableName(Sender: TObject;
      DataSet: TDataSet; var TableName: String);
    procedure prvObjavVerstkaDifferenceGetTableName(Sender: TObject;
      DataSet: TDataSet; var TableName: String);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  publData: TpublData;

implementation

uses main, dm, globals, accessRights;

{$R *.dfm}

procedure TpublData.qryObjavForNaborSDS_NAMEGetText(Sender: TField;
  var Text: String; DisplayText: Boolean);
begin
	if (Sender.DataSet.FieldByName('SD_TYPE').AsInteger = SD_TYPE_DOUBLE) then
		Text := ''
	else
		Text := Sender.AsString;
end;

procedure TpublData.qrySdelkaForKorrekturaSD_COMMENTGetText(Sender: TField;
  var Text: String; DisplayText: Boolean);
begin
	Text := Sender.AsString;
end;

procedure TpublData.qryChangeCountLIST_TEXTGetText(Sender: TField;
  var Text: String; DisplayText: Boolean);
begin
	with Sender.DataSet do
		Text := FieldByName('RB_NAME').AsString + ' (' + FieldByName('CHANGE_COUNT').AsString + ' изменений)';
end;

procedure TpublData.cdsSdelkaSverstanaOBJAV_TEXTGetText(Sender: TField;
  var Text: String; DisplayText: Boolean);
begin
	Text := Sender.AsString;//copy(Sender.Text,1,255);
end;

procedure TpublData.qryFindOldObjav1OB_TEXTGetText(Sender: TField;
  var Text: String; DisplayText: Boolean);
begin
	Text := Sender.AsString;
end;

procedure TpublData.prvObjavOrderGetTableName(Sender: TObject;
  DataSet: TDataSet; var TableName: String);
begin
    TableName := 'OBJAV';
end;

procedure TpublData.prvObjavSverstanoGetTableName(Sender: TObject;
  DataSet: TDataSet; var TableName: String);
begin
    TableName := 'OBJAV';
end;

procedure TpublData.prvObjavVerstkaDifferenceGetTableName(Sender: TObject;
  DataSet: TDataSet; var TableName: String);
begin
    TableName := 'OBJAV';
end;

end.
